library(tidyverse)
library(rtracklayer)
library(ggplot2)

gtf_df <- rtracklayer::import("reference.gtf") %>% as.data.frame()
exons <- gtf_df %>% filter(type == "exon")

sites_5prime <- exons %>%
  group_by(transcript_id) %>%
  mutate(last_exon = max(exon_number)) %>%
  ungroup() %>%
  filter(exon_number != last_exon) %>%
  sample_n(10000) %>%
  mutate(
    intron_start = ifelse(strand == "+", end + 1, start - 1),
    start = ifelse(strand == "+", intron_start - 3, intron_start - 5),
    end   = ifelse(strand == "+", intron_start + 5, intron_start + 3),
    score = 1
  )

sites_3prime <- exons %>%
  filter(exon_number != 1) %>%
  sample_n(10000) %>%
  mutate(
    intron_end = ifelse(strand == "+", start - 1, end + 1),
    start = ifelse(strand == "+", intron_end - 11, intron_end - 1),
    end   = ifelse(strand == "+", intron_end + 1, intron_end + 11),
    score = 1
  )

rtracklayer::export(sites_5prime, "sites_5prime.bed")
rtracklayer::export(sites_3prime, "sites_3prime.bed")

# Assume fasta files already generated by bedtools externally
seqs_5prime <- rtracklayer::import("sites_5prime.fa", format = "FASTA") %>% as.character()
seqs_3prime <- rtracklayer::import("sites_3prime.fa", format = "FASTA") %>% as.character()

five_prime_ss <- sapply(seqs_5prime, function(seq) {
  if (nchar(seq) >= 5) substr(seq, 4, 5) else NA
})

five_ss_freq_combined <- data.frame(
  five_prime_ss = five_prime_ss,
  stringsAsFactors = FALSE
) %>%
  group_by(five_prime_ss) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(
    five_prime_ss = ifelse(five_prime_ss == "GT", "GT", "other")
  ) %>%
  group_by(five_prime_ss) %>%
  summarise(n = sum(n), .groups = "drop") %>%
  mutate(
    percentage = n / sum(n) * 100,
    label = paste0(five_prime_ss, " (", round(percentage, 1), "%)")
  )

# Plot 5' ss
pdf("five_prime_ss_distribution_combined.pdf", width = 8, height = 6)
ggplot(five_ss_freq_combined, aes(x = "", y = percentage, fill = five_prime_ss)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +
  labs(fill = "5' ss") +
  theme_minimal() +
  geom_text(aes(label = label), position = position_stack(vjust = 0.5), size = 5)
dev.off()

three_prime_ss <- sapply(seqs_3prime, function(seq) {
  if (nchar(seq) >= 12) substr(seq, 11, 12) else NA
})

three_ss_freq_combined <- data.frame(
  three_prime_ss = three_prime_ss,
  stringsAsFactors = FALSE
) %>%
  group_by(three_prime_ss) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(
    three_prime_ss = ifelse(three_prime_ss == "AG", "AG", "other")
  ) %>%
  group_by(three_prime_ss) %>%
  summarise(n = sum(n), .groups = "drop") %>%
  mutate(
    percentage = n / sum(n) * 100,
    label = paste0(three_prime_ss, " (", round(percentage, 1), "%)")
  )

# Plot 3' ss
pdf("three_prime_ss_distribution_combined.pdf", width = 8, height = 6)
ggplot(three_ss_freq_combined, aes(x = "", y = percentage, fill = three_prime_ss)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +
  labs(fill = "3' ss") +
  theme_minimal() +
  geom_text(aes(label = label), position = position_stack(vjust = 0.5), size = 5)
dev.off()
